import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google";

const Nun = Nunito({
  subsets: ['latin'],
  weight: ['500'],
  variable: '--merriweather'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={Nun.className}
      >
        {children}
      </body>
    </html>
  );
}
